### ISSUE TITLE
Typing into Github search cause infinite loop of events

### ISSUE THREAD

**Issue by paulz** [inamiy/Harvest-SwiftUI-Gallery#14]
Here is a video of a state app gets into:

https://twitter.com/iospaulz/status/1221557272884563969

[HarvestLoopBug.mov.zip](https://github.com/inamiy/Harvest-SwiftUI-Gallery/files/4114562/HarvestLoopBug.mov.zip)

I was not able to type into the GitHub search bar as letters were processed in an incorrect order.

**Comment by inamiy** [comment]
Sorry for late reply, thank you for the bug report!
While there may be some logical bug in it, I couldn't reproduce this bug...
It will be great if you can also provide the steps to reproduce.

**Comment by inamiy** [comment]
I think I got how to reproduce your situation:

1. Go to Timer
2. Start Timer
3. Back to main list
4. Go to other screen
5. All events get delayed or malformed due to Timer (heavy task) is still running

**Comment by inamiy** [comment]
I would conclude that this is probably the **limitation of SwiftUI that can't handle too rapid event flows (due to slow view-diffing)**.

Or, SwiftUI's direct state binding (`Binding`) without using `Harvest` may solve the situation.
In that case, using `Harvest` will be the main bottleneck since it's architectural concept (including Redux or Elm) is to let view-renderer (SwiftUI) **recalculate diffs of entire view hierarchy rather than partial hierarchy**.

**Comment by inamiy** [comment]
I'm not sure how other non-Swift frameworks can solve this problem (maybe they can't too?).
It's worth experimenting in future.

**Comment by inamiy** [comment]
#20 (turning off TimeTravel debugging feature) will hopefully fix many UI glitches reported in #14, #15, #16 .

Please let me know if the same issues still occur.
